---
title: "HTML Widgets"
output: 
    html_document:
        css: style.css
---

```{r setup, include=FALSE}
library(svglite)
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, comment="", dev = "svg")
knitr::opts_knit$set(root.dir='..')
```

<div style="line-height: 2em;">

## Distribution
```{r}
source("./rscript/plotting.R")
```

## 模糊容忍
```{r, dev='svg', out.width="400px", out.height="300px"}
p_AT
```

<br> 

## 自我效能
```{r, dev='svg', out.width="400px", out.height="300px"}
p_CF1
```
```{r, dev='svg', out.width="400px", out.height="300px"}
p_CF2
```

## 堅毅
```{r, dev='svg', out.width="400px", out.height="300px"}
p_HD1
```
```{r, dev='svg', out.width="400px", out.height="300px"}
p_HD2
```

## 自省
```{r, dev='svg', out.width="400px", out.height="300px"}
p_RF
```

<br>

## heatmaply
```{r fig.width=6, fig.height=6}
library(heatmaply)
source("./rscript/corr_matrix.R")
hm
```

## pie chart

```{r dev='svglite', fig.width=5.5, fig.height=4}
library(cowplot)
source("./rscript/plotting_descri.R", encoding = "utf-8")
plot_grid(dept, college, nrow=2)
```

<br>

```{r dev='svg' ,fig.width=6, fig.height=4}
plot_grid(gender, grade, ncol=2)
```

<br>

## Score Comparison
```{r dev='svg', fig.height=6}
library(cowplot)
source("./rscript/anova.R", encoding = "utf-8")

plot_grid(gender_box_plot,ntu_box_plot,grade_box_plot, nrow=2, rel_heights = c(1, 1.3))
```

</div>