language: r
pandoc_version: 1.19.2.1

before_install:
  - sudo apt-get install language-pack-zh*    # install Chinese lang support
  - sudo apt-get install chinese*             # install Chinese lang support
  - sudo mkdir /usr/share/fonts/truetype/noto                           # install Chinese font NotoSansCJK TC
  - sudo cp ./NotoSansCJKtc.otf /usr/share/fonts/truetype/noto          # install Chinese font NotoSansCJK TC
  - sudo chmod 755 /usr/share/fonts/truetype/noto/NotoSansCJKtc.otf     # install Chinese font NotoSansCJK TC
  - fc-cache                                                            # install Chinese font NotoSansCJK TC

script: 
  - make ./data
  - travis_wait 30 Rscript -e 'rmarkdown::render_site(input="./website_source", encoding = "UTF-8")'

cache:
  packages: yes
  directories:

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: _site # web output directory 
  on:
    branch: master

