---
title: "HTML Widgets"
---
```{r setup2 , include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, comment="", dev='svg')
knitr::opts_knit$set(root.dir='..')
```


## Distribution
```{r}
source("./rscript/plotting.R")
```

## 模糊容忍
```{r, out.width="400px", out.height="300px"}
p_AT
```

<br> 

## 自我效能
```{r, out.width="400px", out.height="300px"}
p_CF1
```
```{r, out.width="400px", out.height="300px"}
p_CF2
```

## 堅毅
```{r, out.width="400px", out.height="300px"}
p_HD1
```
```{r, out.width="400px", out.height="300px"}
p_HD2
```

## 自省
```{r out.width="400px", out.height="300px"}
p_RF
```

<br>

## heatmaply
```{r fig.width=6, fig.height=6}
library(heatmaply)
source("./rscript/corr_matrix.R")
hm
```

## pie chart
```{r}
library(cowplot)
source("./rscript/plotting_descri.R", encoding = "utf-8")
```
```{r dev='svglite', fig.width=5.5, fig.height=2}
college
```


<br>

```{r fig.width=6, fig.height=4}
plot_grid(gender, grade, ncol=2)
```

<br>

## Score Comparison
```{r fig.height=2.5, fig.width=6}
library(cowplot)
source("./rscript/anova.R", encoding = "utf-8")

plot_grid(gender_box_plot, ntu_box_plot, nrow = 1)
```

```{r fig.height=3, fig.width=3.5}
grade_box_plot
```



```{r}
.packages() %>% write(file = "packages2.txt")
```

